### PR TITLE
Adding dotnet framework 4.8.1 support

### PR DESCRIPTION
**Pull request by johnmccrae**
### Description
Adding a package for .net framework 4.8.1. 

#### Types of changes

- [X] New feature (non-breaking change which adds functionality)

### Checklist:

- [X]  I have read the CONTRIBUTING document.
- [ ]  I have run the pre-merge tests locally and they pass.
- [ ]  I have updated the documentation accordingly.
- [ ]  I have added tests to cover my changes.
- [ ]   All new and existing tests passed.
- [X]  All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by smandaka** [comment]
I am able to build the package but hart file size is just 3kb. 
 
And all the folders under hab\pkgs\core\dotnet-481-dev-pack-x64\0.1.0\20240826055456 are empty. 
like Program Files (x86) and Program Files

**Comment by johnmccrae** [comment]
This appears to be both building a correctly made hart file and installing into the build directories. Can you confirm that? @smandaka

**Comment by smandaka** [comment]
@johnmccrae  I am still getting error, pkg_source value is wrong, every time getting different checksum error for pkg_source. 

Can you change to pkg_source to "https://download.microsoft.com/download/8/1/8/81877d8b-a9b2-4153-9ad2-63a6441d11dd/NDP481-DevPack-ENU.exe"

And pkg_version is also wrong. It should be $pkg_version="4.8.1"

**Comment by johnmccrae** [comment]
@smandaka Got that taken care of. How's this look?

**Comment by smandaka** [comment]
@johnmccrae  Now the package is building. 
But found some other issues:  
1)     $pkg_bin_dirs=@("Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\x64")
        $pkg_lib_dirs=@("Program Files (x86)\Windows Kits\NETFXSDK\4.8.1\Lib\um\x64")
        Both the folders are empty, I think we should change the paths from "Program Files (x86)" to "Program Files" as  
        "Program Files\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\x64" and "Program Files\Windows Kits\NETFXSDK\4.8.1\Lib\um\x64" have files in it.
        
 2) Package name should be dotnet-481-dev-pack instead of dotnet-481-dev-pack-x64.
 
 3) $pkg_origin="chef". If we are adding package in core-packages repo, pkg_origin should be "core"

**Review by smandaka — APPROVED** [review]
Looks good to me.

**Pull request merged**
